### PR TITLE
feat: faucet

### PR DESCRIPTION
**Pull request by Keyrxng**
Resolves https://github.com/ubiquity/pay.ubq.fi/issues/142

### CODE REVIEW

**Comment by 0x4007** [comment]
You should always link the pull request to the open issue. If its in a different repository, then you paste in the full URL after the "Resolves" keyword.

**Comment by rndquu** [comment]
@Keyrxng 

1. Pls review https://github.com/ubq-testing/faucet/pull/1 and merge if it's fine
2. I can't run the worker locally via `yarn start` because I get the `Worker exceeded resource limits` error all the time. Do you have such an issue?

**Comment by Keyrxng** [comment]
Sorry for the slow reply been a busy week, trying to scale out of my 9-5 at the minute. 

I'll check things this evening.

As for 2, yeah I was able to fire maybe 3 transactions locally before I hit that same issue, restarting the server gave me another few attempts. A side-effect of the local env I assumed, my actual worker doesn't have any such issues.

**Comment by rndquu** [comment]
> Sorry for the slow reply been a busy week, trying to scale out of my 9-5 at the minute.
> 
> I'll check things this evening.
> 
> As for 2, yeah I was able to fire maybe 3 transactions locally before I hit that same issue, restarting the server gave me another few attempts. A side-effect of the local env I assumed, my actual worker doesn't have any such issues.

You mean there is no `Worker exceeded resource limits` error on a prod worker deployed to cloudflare, right?

**Comment by Keyrxng** [comment]
Yeah rndquu but not exactly, done a little digging and cpu intensive workers can get that error in prod but mine hasn't at least for the interactions I've put to it and comparing that against the ENS implementation the throughput on theirs vs ours would be minimal so afaik it's only because it's a dev env it's throwing that.

**Review by rndquu — APPROVED** [review]

**Pull request merged**
